# Generated by Django 5.1.3 on 2025-01-29 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดกิจกรรม'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='วันที่เริ่มจัดกิจกรรม'),
        ),
    ]
