# Generated by Django 5.1.3 on 2025-02-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityregistration',
            options={'ordering': ['-registration_date'], 'verbose_name': 'รูปหลักฐานการลงทะเบียนทั้งหมด', 'verbose_name_plural': 'รูปหลักฐานการลงทะเบียนทั้งหมด'},
        ),
    ]
