# Generated by Django 5.1.3 on 2024-11-30 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'กิจกรรม', 'verbose_name_plural': 'กิจกรรมทั้งหมด'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้างกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='วันที่จัดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='รายละเอียดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activity', verbose_name='กิจกรรม'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='participated',
            field=models.BooleanField(default=False, verbose_name='สถานะการเข้าร่วม'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='นักศึกษา'),
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_images/', verbose_name='รูปภาพ')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.activity', verbose_name='กิจกรรม')),
            ],
            options={
                'verbose_name': 'รูปภาพกิจกรรม',
                'verbose_name_plural': 'รูปภาพทั้งหมด',
            },
        ),
    ]
