# Generated by Django 5.1.3 on 2025-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_activity_options_alter_activity_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ผู้ใช้', 'verbose_name_plural': 'ผู้ใช้ทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'การเข้าร่วมกิจกรรม', 'verbose_name_plural': 'การเข้าร่วมกิจกรรมทั้งหมด'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'นักศึกษา'), ('admin', 'ผู้ดูแลระบบ')], default='student', max_length=10, verbose_name='ประเภทผู้ใช้'),
        ),
    ]
