# Generated by Django 5.1.3 on 2025-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_activityregistration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityregistration',
            name='proof_upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
