# Generated by Django 5.1.3 on 2025-01-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_options_alter_participation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'นักศึกษา'), ('teacher', 'อาจารย์'), ('admin', 'ผู้ดูแลระบบ')], default='student', max_length=10, verbose_name='ประเภทผู้ใช้'),
        ),
    ]
