# Generated by Django 5.1.3 on 2025-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'ยังไม่อนุมัติ'), ('approved', 'อนุมัติแล้ว')], default='pending', max_length=10, verbose_name='สถานะการลงทะเบียน'),
        ),
    ]
