# Generated by Django 5.1.5 on 2025-05-05 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0005_participation_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='วันที่และเวลา')),
                ('action', models.CharField(choices=[('CREATE', 'สร้าง'), ('UPDATE', 'แก้ไข'), ('DELETE', 'ลบ'), ('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ'), ('APPROVE', 'อนุมัติ'), ('REJECT', 'ไม่อนุมัติ'), ('UPLOAD', 'อัพโหลดไฟล์'), ('DOWNLOAD', 'ดาวน์โหลดไฟล์'), ('OTHER', 'อื่นๆ')], max_length=20, verbose_name='การกระทำ')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='โมดูล')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='สถานะ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บันทึกการใช้งานระบบ',
                'verbose_name_plural': 'บันทึกการใช้งานระบบ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
