# Generated by Django 5.1.5 on 2025-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='รหัสผ่าน (ไม่เข้ารหัส)'),
        ),
    ]
