# Generated by Django 5.1.5 on 2025-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_password_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(default=30, verbose_name='จำนวนผู้เข้าร่วมสูงสุด'),
        ),
    ]
