# Generated by Django 5.1.3 on 2025-02-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_activityregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.activity'),
        ),
    ]
