# Generated by Django 5.1.5 on 2025-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proof_images/'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='proof_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
