# Generated by Django 5.1.5 on 2025-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_activityregistration_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(default=0, help_text='กำหนดเป็น 0 หากไม่ต้องการจำกัดจำนวนผู้เข้าร่วม', verbose_name='จำนวนผู้เข้าร่วมสูงสุด'),
        ),
    ]
